// Auth related actions
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

// Hipster calculation related
export const FETCH_HIPSTER_DATA = 'FETCH_HIPSTER_DATA';
export const FETCH_HIPSTER_DATA_SUCCESS = 'FETCH_HIPSTER_DATA_SUCCESS';
export const FETCH_HIPSTER_DATA_FAILURE = 'FETCH_HIPSTER_DATA_FAILURE';
export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const FETCH_ARTISTS_FAILURE = 'FETCH_ARTISTS_FAILURE';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';

// Site related actions
export const SET_LOADING_MESSAGE = 'SET_LOADING_MESSAGE';

// User related actions
export const SUBMIT_CONTACT_EMAIL = 'SUBMIT_CONTACT_EMAIL';
export const SUBMIT_CONTACT_SUCCESS = 'SUBMIT_CONTACT_SUCCESS';
export const SUBMIT_CONTACT_ERROR = 'SUBMIT_CONTACT_ERROR';
